language: android
jdk:
- oraclejdk8
android:
  components:
  - android-19
before_install:
- chmod +x gradlew
addons:
  sonarqube:
    organization: mmyumu-github
    branches:
    - master
    - develop
    token:
      secure: "wSJeViwrXnDneXdXx5S0gEwRNUwy+C6Dvj171KKbENn5XCT0tJhK0/Kd7KyONGdlEV4le56hZ7MzfHZD8SY9LR1wK8iEUbRajO6yVqhrRZBCHIulrBeHE6CPDxLGD5TyXUhGQXDskq0Wl05HAVqTqkC+C5lWwG5v5mfwvwPI00NxRLF0zYNBJ93s8HEl3rJ+xIHbaxvAj9sbd6r0XJ7OH2lHQx0tqeiAIGklacryAieIBF1V/JQYfhu7p+Mo78YJqLN5S2morENpHHLNJBgeIFv/Bcwv2yoe0R+EHoO7FpwOh0EVCIpBPdgZXh9hYinFJaI9VodZ/mki6avPqV7frJJPpBQMC4LfRpDldc7JVIVgJVjAjjpj6zr57ZSv4QcgVihxNrhHuduGNC3zB6p8NPTBeaKDYaXvwbs7ApGdcOy2rLe/M/yFhOGcfjxWWHyXET2em4agKBrihQpcvcnGbZrA2DaZkfC69Ob+ws4lX+jW5Irq8REdbMy6JkWzGdqJ27QJaqcLEuSYvuEgcW4KgZ3uxNS1ilrAtiV4aCh6wDc91H3++E8QE3YcWyk50Zya5vW+Fzahz1qK8tJWjw4ZoJ+VZ97/guvvMRZTnUoN3xe9yB0zeT1Sehp3pJOVtL98TF0X8qnnZoEuI4xWARjePQsVy9X/q0C5j6IqdWLBzrA="
    github_token:
      secure: "HhOw2yVdQ9C+gU74qBlSCOsrMPMRzOcIgcWeu4fFy5XUq1GHJvUHZwPw4JJqSaeDxkN7F3qc3gPKULBi4TZ54rZ58QrGwGz6aBi2rZvQdeN4Rrq5dWXpxsbmdkmTnUqWiekBKIKPNayiUIu7qx8Sd90+lqZRGn0levoXjwJu/dG4ksftjdEECFQ7Em9SB5XZijmaHHUL+c739aecckOIz/BsSl6Jo9XW02qxE6ul+ijow+BrvZRqo9Is3Wy29MOqlEXvrez90ffNPSBuwNPa5+efWAbtBOjoLGWUYieVG31Jj122y+L1NeU++cMvYdMZCY2P0ClX9E/5Ox12a2/nuR59JB9z8+lY9YtsD+KnVRG3JL1TzT+lbKTkj+9563Djfc6hz7aUssvvUfnMCLfTPz+V71xxjf6X71ZoOVlpzHO7tyAm/B8nMqEvkdZMwM3W/3uoF8Lv06KuYvCHNN0D12f8MbgOSBR35lFGIKgyb+gGBFVHCSjPacuhPZoR/6UUL2C3wWjNuCVDD4YWsf6EkW07snRigs8yqxwl9b0xfrj6cbQK21weVmSYasVd1Dq3PicVXeK3TyD+3aROtaiulOHg2EIz1SO0cvTzJrGRHCQLnxhj4s9/SzcbXr6NHzIWpn1LSjj9j/8CvU2vJg5h8nYN/cWM5f6+Sihnh8H0cII="
script:
- "./gradlew :core:test"
- sonar-scanner